-- Migration 002: Schema Expansion for Questionnaire, Photos, Matches, and Messaging

-- 1. Table: questionnaire_answers
-- Stores the smart questionnaire results for each user.
-- The questionnaire is completed once during onboarding.
CREATE TABLE IF NOT EXISTS public.questionnaire_answers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
    answers jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Table: profile_photos
-- Allows users to upload and manage multiple photos.
CREATE TABLE IF NOT EXISTS public.profile_photos (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    url text NOT NULL,
    display_order integer DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Table: matches
-- Stores the 1-on-1 matches generated by the system.
-- Each user sees only one best match at a time.
CREATE TABLE IF NOT EXISTS public.matches (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_a_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_b_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    compatibility_score integer CHECK (compatibility_score >= 0 AND compatibility_score <= 100),
    compatibility_reasons text[], -- Array of strings explaining why it's a good match
    icebreaker_hint text, -- AI or system generated icebreaker
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'chat_started', 'unmatched')),
    expires_at timestamptz NOT NULL DEFAULT (now() + interval '72 hours'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT unique_user_pair CHECK (user_a_id < user_b_id),
    UNIQUE (user_a_id, user_b_id, status) -- Prevents multiple active matches for the same pair
);

-- 4. Table: conversations
-- Created when a match transition to 'chat_started'.
CREATE TABLE IF NOT EXISTS public.conversations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    match_id uuid UNIQUE REFERENCES public.matches(id) ON DELETE SET NULL,
    user_a_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_b_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    last_message_at timestamptz DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 5. Table: messages
-- Real-time chat messages between matched students.
CREATE TABLE IF NOT EXISTS public.messages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 6. Enable RLS
ALTER TABLE public.questionnaire_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 7. Policies: questionnaire_answers
CREATE POLICY "Users can manage their own questionnaire answers"
    ON public.questionnaire_answers FOR ALL
    USING (auth.uid() = user_id);

-- 8. Policies: profile_photos
CREATE POLICY "Users can manage their own profile photos"
    ON public.profile_photos FOR ALL
    USING (auth.uid() = user_id);

CREATE POLICY "Users can view photos of their matches"
    ON public.profile_photos FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.matches
            WHERE status = 'active'
            AND ((user_a_id = auth.uid() AND user_b_id = profile_photos.user_id)
                 OR (user_b_id = auth.uid() AND user_a_id = profile_photos.user_id))
        )
        OR EXISTS (
            SELECT 1 FROM public.conversations
            WHERE (user_a_id = auth.uid() AND user_b_id = profile_photos.user_id)
               OR (user_b_id = auth.uid() AND user_a_id = profile_photos.user_id)
        )
    );

-- 9. Policies: matches
CREATE POLICY "Users can view their own matches"
    ON public.matches FOR SELECT
    USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);

-- 10. Policies: conversations
CREATE POLICY "Users can view their own conversations"
    ON public.conversations FOR SELECT
    USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);

-- 11. Policies: messages
CREATE POLICY "Users can view messages in their conversations"
    ON public.messages FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.conversations
            WHERE id = messages.conversation_id
            AND (user_a_id = auth.uid() OR user_b_id = auth.uid())
        )
    );

CREATE POLICY "Users can send messages to their conversations"
    ON public.messages FOR INSERT
    WITH CHECK (
        auth.uid() = sender_id AND
        EXISTS (
            SELECT 1 FROM public.conversations
            WHERE id = messages.conversation_id
            AND (user_a_id = auth.uid() OR user_b_id = auth.uid())
        )
    );

-- 12. Triggers for updated_at
CREATE TRIGGER set_questionnaire_answers_updated_at
    BEFORE UPDATE ON public.questionnaire_answers
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_matches_updated_at
    BEFORE UPDATE ON public.matches
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 13. Indexes
CREATE INDEX IF NOT EXISTS idx_questionnaire_user_id ON public.questionnaire_answers(user_id);
CREATE INDEX IF NOT EXISTS idx_profile_photos_user_id ON public.profile_photos(user_id);
CREATE INDEX IF NOT EXISTS idx_matches_users ON public.matches(user_a_id, user_b_id);
CREATE INDEX IF NOT EXISTS idx_conversations_users ON public.conversations(user_a_id, user_b_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages(conversation_id);
